# Book settings
title: Deep Learning for Molecules and Materials
author: Andrew D. White
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

html:
  favicon                   : "favicon.png"  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : false  # Whether to add a link to your repository button
  extra_navbar              : Made with <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : <a href="http://thewhitelab.org">thewhitelab.org</a> <div id="wh-modal"> <button class="wh-venti-button" aria-label="close modal" id="wh-modal-close">✕</button> <img id="wh-modal-img"> </div>  # Will be displayed underneath the footer.
  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/

  # Information about where the book exists on the web
repository:
  url                       : https://github.com/quanta-mental/Research  # Online location of your book

launch_buttons:
  colab_url: "https://colab.research.google.com"

parse:
  myst_extended_syntax: true

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

execute:
  timeout: -1